Repository zer0Kerbal/SimpleConstruction, pull requests merged in 2022-03, with the labels that each got.

#70 Update en-us.cfg
  GameData/SimpleConstruction/Localization/en-us.cfg
Labels: issue: text, state: approved

#81 Update B9TankTypes.cfg
  GameData/SimpleConstruction/Compatibility/SimpleConstruction/B9TankTypes.cfg
Labels: issue: compatibility/patch, state: approved

#82 4.0.99.3-prerelease <Bucketful of Sand>
  GameData/SimpleConstruction/Compatibility/B9PartSwitch/B9TankTypes.cfg
  GameData/SimpleConstruction/Compatibility/B9PartSwitch/B9TanksSwitch.cfg
  GameData/SimpleConstruction/Compatibility/CommunityCategoryKit.cfg
  GameData/SimpleConstruction/Compatibility/Foundations.cfg
  GameData/SimpleConstruction/Compatibility/InterstellarFuelSwitch.cfg
  GameData/SimpleConstruction/Compatibility/KerbalInventorySystem.cfg
  GameData/SimpleConstruction/Compatibility/KerbalPlanetaryBaseSystems/KKAOSS_Smelter.cfg
  GameData/SimpleConstruction/Compatibility/KerbalPlanetaryBaseSystems/KKAOSS_Workshop.cfg
  GameData/SimpleConstruction/Compatibility/KerbalPlanetaryBaseSystems/KerbalPlanetaryBaseSystems.cfg
  GameData/SimpleConstruction/Compatibility/StationPartsExpansionRedux.cfg
  GameData/SimpleConstruction/Compatibility/USI-Kontainers.cfg
  GameData/SimpleConstruction/Compatibility/ghostparts.cfg
  GameData/SimpleConstruction/Config/ExperienceTraits.cfg
  GameData/SimpleConstruction/Config/Kerbal.cfg
  GameData/SimpleConstruction/Config/Recipes.cfg
  GameData/SimpleConstruction/Config/Resources.cfg
  GameData/SimpleConstruction/Config/SeatTasks.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/CrewedPods.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/DockingPorts.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/Drills.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/GrapplingDevice.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/ISRU.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/Launchclamps.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/ScienceLabs.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/Tanks.cfg
  GameData/SimpleConstruction/Localization/en-us.cfg
  GameData/SimpleConstruction/SimpleConstruction.version
  GameData/SimpleConstruction/changelog.md
  GameData/SimpleConstruction/readme.htm
  SimpleConstruction.version
  changelog.md
  docs/ReleaseNotes/4.0.99.3.md
  json/mod.json
Labels: semantic: prerelease

#85 84 bug elxxxskill log spam
  GameData/SimpleConstruction/Config/ExperienceTraits.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/GrapplingDevice.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/Launchclamps.cfg
Labels: bug 🐛, issue: config, type: fix, type: pull request

#90 SimpleConstruction! (SCON) 4.0.99.4-prerelease <% Bugs>
  GameData/SimpleConstruction/Config/ExperienceTraits.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/GrapplingDevice.cfg
  GameData/SimpleConstruction/Config/SimpleConstruction/Launchclamps.cfg
Labels: semantic: prerelease
